### PR TITLE
add conditional if all gene counts are 0

### PR DESCRIPTION
**Pull request by evanbiederstedt**
Related to this issue: https://github.com/hms-dbmi/conos/issues/49

Fixes case whereby if all cells have gene count 0, then all cells plotted red. Corrected such that all cells plotted gray. 

Previously (from @rrydbirk):

```
library(conos)
library(Matrix)
library(magrittr)
library(pagoda2)

sample1 <- rsparsematrix(1e3,2e3, 1) %>% abs()   
sample2 <- rsparsematrix(1e3,2e3, 1) %>% abs()

colnames(sample1) <- 1:2e3
colnames(sample2) <- 1:2e3

rownames(sample1) <- sapply(1:1e3, function(a) paste0("A" ,a))
rownames(sample2) <- sapply(1:1e3, function(a) paste0("B", a))

sample1[1:1e3] <- 0 #gene "1" is 0
sample2[1:1e3] <- 0

panel.preprocessed <- lapply(list(sample1 = sample1, sample2 = sample2) %>% lapply(t), basicP2proc, n.cores=8, min.cells.per.gene=0, n.odgenes=5e2, get.largevis=FALSE, make.geneknn=FALSE, min.transcripts.per.cell = 0, get.tsne=F)

con <- Conos$new(panel.preprocessed)
con$buildGraph()
con$embedGraph()
con$findCommunities()
con$plotGraph(gene="1", show.legend=TRUE)
```

outputs this: 
before_red

After re-installing sccore with the fix in this PR, the output is this:
after_gray90

### CODE REVIEW

**Comment by evanbiederstedt** [comment]
BTW, @pkharchenko 

https://github.com/kharchenkolab/sccore/blob/bugfix/plot_gene_count0/R/plots.R#L75-L82
```
 # symmetrize the range if needed
  if(length(color.range)==1 && color.range=='symmetric') {
    if(prod(zlim)<0) {
      zlim <- c(-1,1)*max(abs(zlim))
    } else {
    }
  }
  if(is.null(midpoint)) midpoint <- sum(zlim)/2;
```
Question: I think we could just remove the else conditional, no?

**Comment by rrydbirk** [comment]
Hi Evan

Thanks for this! Although it fixes the problem, I'm now thinking why we're even allowing plotting when counts are 0. Shouldn't they actually be treated as empty/NA?

/Rasmus

**Comment by evanbiederstedt** [comment]
Hi @rrydbirk 

It's certainly possible to do that, with changes here: https://github.com/kharchenkolab/sccore/blob/bugfix/plot_gene_count0/R/plots.R#L171-L176

I guess the question is one for analysis: is it easier for users to see all cells plotted (even when some cells have counts=0) or remove those cells entirely for plots? That is, are there cases when removing these data points entirely for visualization is misleading?

I'm open to do this; probably requires a larger discussion with @VPetukhov and @pkharchenko

**Comment by VPetukhov** [comment]
Hi Evan,
Does it actually work on normal cases? To my understanding, `prod(zlim)==0` could happen for `zlim = c(0, 10)`, for example. Shouldn't there be `max(abs(zlim)) == 0` instead? Or do I miss something?

> Shouldn't they actually be treated as empty/NA?

@rrydbirk , why should they? Zeros are zeros, not the non-available measurements, as far as I understand the usecase. If we want to introduce NAs for the cells that don't have this gene measured, doing it upstream in the Conos would be a much better strategy. Though I'm uncertain whether we want to do that, as too often "not measured" actually means "around-zero-expression".

**Comment by evanbiederstedt** [comment]
@VPetukhov You're entirely right---this is my mistake. I first worked this out on the `sccore` master branch, which didn't take into account the `val2ggcol()` rewrite. 

But it's possible the `prod()` idea doesn't work always, i.e. 
https://github.com/kharchenkolab/sccore/blob/bugfix/plot_gene_count0/R/plots.R#L75-L82

```
 # symmetrize the range if needed
  if(length(color.range)==1 && color.range=='symmetric') {
    if(prod(zlim)<0) {
      zlim <- c(-1,1)*max(abs(zlim))
    } else {
    }
  }
  if(is.null(midpoint)) midpoint <- sum(zlim)/2;
```
For a symmetric `color.range`, `prod(zlim)` is always negative?

**Comment by VPetukhov** [comment]
Thanks! I also struggle understanding the whole logic of `val2ggcol. @pkharchenko , could you answer the Evan's question?

**Review by VPetukhov — APPROVED** [review]

**Comment by rrydbirk** [comment]
> ... too often "not measured" actually means "around-zero-expression".

Exactly, but in my mind there's a huge difference between plotting all NAs and 0s although they may be ~same. But for now, I think Evan's fix is enough.

**Review by rrydbirk — APPROVED** [review]

**Comment by pkharchenko** [comment]
It’s supposed to symmetries the range for vectors that span 0.
Vectors that are squarely in the positive or negative territory are not symmetrized.
I couldn’t tell from the thread if something was not working, or if this was just a question about logic.
btw the alternative to this is to explicitly set a midpoint (at 0 for symmetrize, and sum(range)/2 otherwise)

**Comment by evanbiederstedt** [comment]
> I couldn’t tell from the thread if something was not working, or if this was just a question about logic.

More of a question of logic to make sure that it works as intended. The trailing else statement also made me think it was unfinished perhaps---that should probably be removed.

**Comment by evanbiederstedt** [comment]
I think maybe we've been waiting for @pkharchenko to chip in here, but I think we've settled things

I'll merge. If there are issues, we can always revert.

**Pull request merged**
